FROM python:3.10.11-slim


WORKDIR /app

# Устанавливаем системные зависимости (ffmpeg нужен для video_ai_service)
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*


# Копируем файлы зависимостей
COPY requirements.txt .


# Устанавливаем зависимости Python
RUN pip install  -r requirements.txt

# Копируем все файлы проекта
COPY . .

# Указываем порт, который будет использоваться
EXPOSE 8001

# Команда для запуска приложения
CMD   alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001
