"""remove vk_id

Revision ID: 02bf0596b513
Revises: c4d1e2f3a5b6
Create Date: 2026-05-13 21:36:23.993730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "02bf0596b513"
down_revision: Union[str, None] = "c4d1e2f3a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_vk_id", table_name="users")
    op.drop_column("users", "vk_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("vk_id", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_users_vk_id", "users", ["vk_id"], unique=True)
    # ### end Alembic commands ###
