"""add audio_url to steps

Revision ID: 9c67d7320691
Revises: a21f592084ce
Create Date: 2026-04-09 17:23:46.605870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9c67d7320691"
down_revision: Union[str, None] = "a21f592084ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_steps",
        sa.Column(
            "audio_url",
            sa.Text(),
            nullable=True,
            comment="Ссылка на сгенерированную озвучку (S3)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training_steps", "audio_url")
    # ### end Alembic commands ###
