"""init

Revision ID: a21f592084ce
Revises: 
Create Date: 2026-03-27 15:27:14.886560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a21f592084ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('value'),
    sa.UniqueConstraint('label')
    )
    op.create_table('tags',
    sa.Column('value', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('value'),
    sa.UniqueConstraint('label')
    )
    op.create_table('typesactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('registration_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False, comment='Название курса'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание курса'),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_creator_id'), 'courses', ['creator_id'], unique=False)
    op.create_table('trainings',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Заголовок тренинга'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание тренинга'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='id ссылка на создателя'),
    sa.Column('level_id', sa.Integer(), nullable=True, comment='id ссылка на уровень прохождения тренинга'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Ожидаемое время прохождения тренинга в минутах'),
    sa.Column('publish', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Опубликован ли тренинг'),
    sa.Column('skip_steps', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Пропуск шагов'),
    sa.Column('hints_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Разрешены ли подсказки в прохождении'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.value'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('course_trainings',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'training_uuid')
    )
    op.create_table('training_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_publications_access_token'), 'training_publications', ['access_token'], unique=True)
    op.create_table('training_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=True),
    sa.Column('parent_step_id', sa.Integer(), nullable=True, comment='ID родительского шага для вложенной структуры'),
    sa.Column('area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('instruction_html', sa.Text(), nullable=True, comment='Задание для ученика (безопасный HTML)'),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('photo_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['typesactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_step_id'], ['training_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_tags',
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.Column('tag_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_value'], ['tags.value'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_uuid', 'tag_value')
    )
    op.create_table('training_passage_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('wrong_attempts_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['training_publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_passage_attempts_publication_id'), 'training_passage_attempts', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_passage_attempts_publication_id'), table_name='training_passage_attempts')
    op.drop_table('training_passage_attempts')
    op.drop_table('training_tags')
    op.drop_table('training_steps')
    op.drop_index(op.f('ix_training_publications_access_token'), table_name='training_publications')
    op.drop_table('training_publications')
    op.drop_table('course_trainings')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_courses_creator_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('typesactions')
    op.drop_table('tags')
    op.drop_table('levels')
    # ### end Alembic commands ###
