"""Add icon to Training

Revision ID: cdbb8c37e36a
Revises: e8f9a0b1c2d3
Create Date: 2026-06-05 23:24:36.209804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cdbb8c37e36a"
down_revision: Union[str, None] = "e8f9a0b1c2d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trainings",
        sa.Column("icon", sa.String(), nullable=True, comment="URL иконки тренинга"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trainings", "icon")
    # ### end Alembic commands ###
